### ISSUE TITLE
Give option for more discreet notification when a thread is moved

### ISSUE THREAD

**Issue by Raph33** [gabrieljackson/mattermost-plugin-wrangler#101]
The bot's message when a thread is moved to a different channel takes a lot of space, it would be great if there was a way to have it be just a simple message that says "A thread has been moved to this channel" (and "this channel" could be hyperlinked to the thread's new location). If folks find it helpful to have all the information that is currently included in the message, this could be set in a plugin setting to show a short or long notification message.

**Comment by gabrieljackson** [comment]
Thanks for the input. This seems reasonable enough so I will make sure it gets added.

**Comment by gabrieljackson** [comment]
Heya @Raph33.

The move thread message has been cleaned up some. It will now be `A thread with X messages have been moved: LINK_HERE` as long as the user moving the thread deselects the option to include the root message in the summary.

This change will be included in the next wrangler release. Please let me know if you have any questions.
