### ISSUE TITLE
All limited channel members can move posts with the Wrangler plugin !!!!!

### ISSUE THREAD

**Issue by majidit** [gabrieljackson/mattermost-plugin-wrangler#112]
Hello to all friends

All limited channel members can move posts with the Wrangler plugin !!!!

This has caused problems in our management channel several times ....

Please fix this

Thankful

@gabrieljackson @jfrerich

**Comment by gabrieljackson** [comment]
Hello @majidit,

Have you configured the plugin to restrict who can use it in the plugin settings in the system console? There are quite a few ways to do this including restricting users by email address.

**Comment by gabrieljackson** [comment]
At this time, the existing plugin settings are meeting the requirements for controlling access to Wrangler. If you need to individually control who should use it, then I would propose adding each user individually via the email domain text box. An example of how this can be done can be found here: https://github.com/gabrieljackson/mattermost-plugin-wrangler#configuration-options

Please let me know if you have any other questions.
