### ISSUE TITLE
When a post is moved that begins with a header, the reply post by Wrangler renders the whole post as a header

### ISSUE THREAD

**Issue by mickmister** [gabrieljackson/mattermost-plugin-wrangler#115]
![image](https://user-images.githubusercontent.com/6913320/125858124-55a732fc-3a5b-4765-aed5-fa32377db44d.png)

![image](https://user-images.githubusercontent.com/6913320/125858151-d14336bd-14e5-4d97-b046-e792fd961067.png)

**Comment by mickmister** [comment]
Link to post with the issue https://community-daily.mattermost.com/core/pl/txhi67pr8pbi7jwbbagmj1csnh

**Comment by gabrieljackson** [comment]
Thanks for the heads-up! This will be fixed in the next release.
