### ISSUE TITLE
Allowing customizable Bot-Messages

### ISSUE THREAD

**Issue by Haliax** [gabrieljackson/mattermost-plugin-wrangler#127]
After attaching a message to a thread or moving/copying a thread, a bot message is sent to the author of that message.

**Problems with that message:**
1. The message is not customizable. 
2. `someone wrangled one of your messages` is very unclear. For non native speakers and people not knowing about "wrangler", this message does not make sense.
2.  It is not clear which moderator moved the message. Therefore not allowing the author to contact the executing moderator.

**Possible fix:**
1. It would be nice to change `someone` to the name of the executing moderator.
2. It would be nice to make the message customizable.

**Comment by Haliax** [comment]
Functionality enabled with: #128

**Comment by gabrieljackson** [comment]
Thanks again for the contribution.
