### ISSUE TITLE
Users get a white screen on browser & app when activated in 7.1/7.2

### ISSUE THREAD

**Issue by jprusch** [gabrieljackson/mattermost-plugin-wrangler#140]
Some users are experiencing a white /empty screen with Wrangler enabled in 7.1/7.2

I disabled all plugins & enabled them one-by-one. Apparently, when enabling Wrangler the issue came back.

Server logs are empty. The issue doesn't affect all users, but I got messages from at least three.

**Comment by gabrieljackson** [comment]
Hey @jprusch, there was a conflict in older versions of Mattermost when running Wrangler. This should be resolved now when running an up-to-date version of the plugin and Mattermost server.

If users encounter any white screens in an updated environment then it would be helpful if they could open their web console and provide the errors reported there.

For now I will close out the ticket as all known web conflicts have been resolved.
