### ISSUE TITLE
Commands: allow links to be used in stead of message IDs.

### ISSUE THREAD

**Issue by Haliax** [gabrieljackson/mattermost-plugin-wrangler#174]
The Wrangler-UI and Mattermost's built-in moderation tools are currently not usable on mobile. The only way to move/copy messages on mobile is to use Slash-Commands. An example command would be `/wrangler attach message message_id_1 message_id_2`.

The only way to get those message IDs on mobile is to use the built-in 'copy link' feature. It gives a link like `https://instance_url/team_id/pl/8w89igrsffyt3ghmwsmsgyeoqe`. To use that ID for the command, a big part of that link has to be removed manually. It has to be done two times on small displays, and scrolling is quite tedious.

I would suggest allowing the use of URLs as parameters as well. With a simple regex, the URLs could be validated and edited to get the ID of the corresponding messages. This would greatly increase the usability of this plugin.

I am down to create a PR with these changes in the upcoming days if there are no reservations against it.

**Comment by Haliax** [comment]
Thanks for the hint! 

For me personally, it is enough. For some our staff-members without tech-background, having to use a `/`-command on mobile and not being able to use the UI is already a pretty big blocker. Having to use multiple commands to attach a thread, results in them not using wrangler at all.

I hope to solve this issue with the PR I just submitted.

**Comment by gabrieljackson** [comment]
Thanks for contributing this! It will be included in the next plugin release.
