### ISSUE TITLE
Moved post does not include uploaded files or copy-pasted images

### ISSUE THREAD

**Issue by mickmister** [gabrieljackson/mattermost-plugin-wrangler#53]
Any uploaded files such as images or audio are not present in the resulting post of moving a message. I think this can be fixed by pointing each file object to the respective new post that it was originally associated with.

**Comment by mickmister** [comment]
I'm entirely sure the solution is possible, as it doesn't make much sense to be able to change the post the file is associated with. So each file may need to be re-processed as a new file.

**Comment by gabrieljackson** [comment]
Hey @mickmister, thank you for the report. I actually recently investigated this, but hadn't gotten around to opening an issue yet.

Your second comment is correct. Wrangler, currently, does not remove file attachment data from the original post list when creating the new "moved" posts. Unfortunately, this doesn't matter as the create-post process silently ignores these files when creating a post. After talking to some Mattermost engineers, it definitely seems like Wrangler will need to manually re-upload files along with any new posts created. This is something I want to support, but in the short term I am going to document it at the very least.

Also, just as a small FYI, emoji reactions also cannot be directly copied when the new post is created. I will be documenting that as well.

**Comment by gabrieljackson** [comment]
The process for re-uploading file attachments was pretty straight-forward so the plugin now supports "moving" files along with their messages.

This will be included in the next release cut.
