### ISSUE TITLE
RPC call OnConfigurationChange to plugin failed

### ISSUE THREAD

**Issue by JtheBAB** [gabrieljackson/mattermost-plugin-wrangler#8]
Hi

I uploaded the plugin to my 5.19.0 instance and activated it. The plugin is showed as running and i can see it in the process list.

But when i type /wrangler it doesn't show up.

In the logs i see this:

`{"level":"error","ts":1579872782.813044,"caller":"mlog/log.go:174","msg":"RPC call OnConfigurationChange to plugin failed.","plugin_id":"com.mattermost.wrangler","error":"connection is shut down"}`

**Comment by gabrieljackson** [comment]
Hey @JtheBAB, I am having some trouble recreating this issue.

I was originally testing on Mattermost `5.18.2` which seemed to work fine. I just recreated my test environment with Mattermost `5.19.1` and uploaded the plugin `0.1.0` tar file from the release page. Once again, the `/wrangler` commands seem to be working as expected.

Did you change any wrangler plugin settings? Right now, mine has no values which is the default.

Test Server Details:
```
Mattermost Version: 5.19.1
Database Schema Version: 5.19.0
Database: mysql

Build Hash: 57f3ca975f565b0235d72ba6eb098e73a25513cd
EE Build Hash: 1268390c0cde16f750b0b6fe62534b82586d595f
Webapp Build Hash: adc1915bf590e3ea8441db6c281c2b01580e87a8
Build Date: Tue Jan 21 23:30:31 UTC 2020
```

**Comment by JtheBAB** [comment]
The process is running:
CGroup: /system.slice/mattermost.service
           ├─8339 /usr/mattermost/bin/mattermost
           ├─8355 plugins/com.mattermost.plugin-todo/server/dist/plugin-linux-amd64
           ├─8377 plugins/matttermost-plugin-newchannelnotify/server/dist/plugin-linux-amd64
           ├─8388 plugins/com.github.matterpoll.matterpoll/server/dist/plugin-linux-amd64
           ├─8398 plugins/com.github.moussetc.mattermost.plugin.giphy/server/dist/plugin-linux-amd64
           ├─8409 plugins/com.github.scottleedavis.mattermost-plugin-remind/server/dist/plugin-linux-amd64
           ├─8419 plugins/mattermost-file-list/server/dist/plugin-linux-amd64
           └─8484 plugins/com.mattermost.wrangler/server/dist/plugin-linux-amd64

My Settings:
![image](https://user-images.githubusercontent.com/42135332/73361670-b613a800-42a5-11ea-9e48-5d4b2a070aff.png)

![image](https://user-images.githubusercontent.com/42135332/73361766-e4918300-42a5-11ea-8c80-1853dd004adc.png)

**Comment by gabrieljackson** [comment]
@JtheBAB, autocomplete is currently not enabled for the `/wrangler` command. If you type `/wrangler` and hit enter you should still see the proper subcommands and help messages.

**Comment by JtheBAB** [comment]
:wallbash:

Thanks
