### ISSUE TITLE
Show channel display name instead of ID in the Wrangler moved thread summary

### ISSUE THREAD

**Issue by gigawhitlocks** [gabrieljackson/mattermost-plugin-wrangler#80]
Today, the channel's real name is displayed instead of the display name of the channel in Wrangler's summary box (see screenshot).

The field that says `town-square` in this screenshot should instead display the Display Name of the channel.
![Screenshot from 2020-06-23 11-46-20](https://user-images.githubusercontent.com/3743903/85431547-51543500-b547-11ea-891e-2d319e4c00fc.png)

**Comment by gabrieljackson** [comment]
Thanks for the suggestion! This behavior was changed and will be included in the next plugin release.
