### ISSUE TITLE
Have the choice to post or not post the original message in the source channel when moving

### ISSUE THREAD

**Issue by mickmister** [gabrieljackson/mattermost-plugin-wrangler#81]
If we are moving a thread from a public channel to a private channel in order to conceal a security issue for example, it may be an issue that the root message is posted by the Wrangler bot at the channel of the original post. We could have a checkbox in the modal that says "include root message in notice" or something similar.

**Comment by gabrieljackson** [comment]
Wrangler now has this option available in the via the slash command and the webapp. It will be available in the next release.
