### ISSUE TITLE
More than one Allowed Email?

### ISSUE THREAD

**Issue by LordMaddhi** [gabrieljackson/mattermost-plugin-wrangler#82]
Hello,
Is it possible to add two or more allowed emails (with different domains) to use this plugin? 

So, for example: 
- abc@gmail.com
- hiebcielh@gmx.net

Best regards :)

**Comment by gabrieljackson** [comment]
Hey there,

Specifying more than one email domain is currently not supported in the plugin, but will be simple to add. I will push up a change to support this behavior for you.

**Comment by LordMaddhi** [comment]
Thank you! :)

**Comment by gabrieljackson** [comment]
I just updated Wrangler to allow for multiple domains/emails with the following format: `domain1.com,domain2.net,domain3.org`.

This will be available in the next plugin release. :)
