### ISSUE TITLE
Inexplicable error message

### ISSUE THREAD

**Issue by fp66** [gabrieljackson/mattermost-plugin-wrangler#86]
I tried to post a post (thread) from a direct message channel to a private channel within the same team. However, I get the error message:

"Wrangler is currently configured to not allow moving messages to different teams"

**Comment by gabrieljackson** [comment]
Hey @fp66,

The plugin configuration has the ability to allow/deny different types of message management. By default, Wrangler does not allow moving messages across teams, but this can easily be enabled in the plugin settings in the system console of Mattermost.

**Comment by fp66** [comment]
Hi @gabrieljackson ,

the point is that I tried to move a message **within the same team**!

**Comment by gabrieljackson** [comment]
Apologies for missing that part of your issue report.

I just tried to replicate this behavior (DM channel to private channel in same team) and was presented with the correct error message initially, but then realized you may have different plugin configuration so I tried it again with the following:

Move from direct message channels: true
Move to different team: false

That indeed presented the team error message you noted. Can you confirm this is the plugin configuration you have?

Regardless, I will see if I can address this. Direct message channels are sort of unique in that they are "teamless" in a way, but I will see what we can do here.

**Comment by gabrieljackson** [comment]
@fp66, I have addressed the issue with conflicting plugin config. The fix will be included in the next release.

**Comment by fp66** [comment]
Thanks a lot, @gabrieljackson!

I don't have access to the the system configuration, therefore I couldn't check the mentioned options. As we only use 1 team in our organization, however, I suppose the configuration is the one you expected.
