### ISSUE TITLE
Allow System Admin or Team Admin to use Wrangler

### ISSUE THREAD

**Issue by nathanaelhoun** [gabrieljackson/mattermost-plugin-wrangler#91]
For now, plugin access is allowed for either all users or users with the "Allowed Email Domain". It could be nice to allow it to System Admin or Team Admin.

For example, we can choose in the settings between "Allowed Email Domain", "System Admins", "System and Team Admins" or "All users".
For Team Admins, it may be trickier : are they authorised to move a thread from a team to another ?

**Comment by gabrieljackson** [comment]
Hey @nathanaelhoun, thanks for the suggestion. You are right that the only form of restriction is via email settings. I will look into checking for admin roles to see if that is viable or not and will get back with you.

**Comment by gabrieljackson** [comment]
Going to close this issue having partially implemented the request. The plugin now supports System Admins only, System Admins and Allowed Email Domains (which can support multiple domains or specific user emails), and All Users.

There are some edge cases supporting Team Admins with other permission settings which can lead to confusing outcomes so I am going to avoid implementing that option for now.
