### ISSUE TITLE
Attaching a thread to a thread

### ISSUE THREAD

**Issue by s-ponta** [gabrieljackson/mattermost-plugin-wrangler#98]
This is a feature request.

In some cases, some people reply by using a thread, but others do not use the thread. As a result, there are some small parts of threads which should be merged into one thread.

I tried to check if this is possible with this plugin, wrangler. Attaching a message in a thread is unavailable from the UI button, but I could move the message by the slash command. But, in this case, associated messages following the moved message was removed completely.

Again, my suggestion is that enabling to attach a thread to thread from both the slash command and UI button is really useful to maintain the message flow in the channel.

**Comment by gabrieljackson** [comment]
This functionality should now be supported via the plugin commands and in the web UI with `thread merging`: https://github.com/gabrieljackson/mattermost-plugin-wrangler/pull/162 and https://github.com/gabrieljackson/mattermost-plugin-wrangler/pull/163

If you haven't already, update the Wrangler plugin to the latest release and enable thread merging in the plugin configuration to use it. Note that merging threads will result in making a single thread that has a message order based on the original message creation timestamps.

Feel free to reach out if you have any questions.

**Comment by camlafit** [comment]
Tested and approved :)
