### ISSUE TITLE
Bug: opening dropdown on a system message crashes the webapp

### ISSUE THREAD

**Issue by nathanaelhoun** [gabrieljackson/mattermost-plugin-wrangler#99]
When opening the dropdown menu on a system message, the webapp crashes

## Reproduce
1. Enable the Wrangler webapp functionality [BETA]
1. Refresh the webapp
1. Click on the dropdown for a system message (i.e. "@someuse has joined the channel")
1. The screen becomes white
1. Refresh to restore the webapp

## Webapp logs
```
TypeError: can't access property "user_id", n is undefined
    lt com.mattermost.wrangler_451a6ce528877b61_bundle.js:26
    Redux 5
    React 2
    k Redux
    React 9
    unstable_runWithPriority scheduler.production.min.js:19
    React 15
    unstable_runWithPriority scheduler.production.min.js:19
    React 2
    j scheduler.production.min.js:17
    onmessage scheduler.production.min.js:14
    EventHandlerNonNull* scheduler.production.min.js:13
    Webpack 13
react-dom.production.min.js:209:194
[Util] handleError::  TypeError: can't access property "user_id", n is undefined index.js:158:36
Uncaught TypeError: can't access property "user_id", n is undefined
```

**Comment by gabrieljackson** [comment]
Thank you for this report. I will investigate and get back with you.

**Comment by gabrieljackson** [comment]
I have identified this issue and will have a few up shortly.

**Comment by gabrieljackson** [comment]
A fix for this issue has been merged and will be part of the next release.

**Comment by nathanaelhoun** [comment]
Great, thanks @gabrieljackson!
